In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
#importing seaborn for statistical plots
import seaborn as sns
# Import Linear Regression machine learning library
from sklearn.linear_model import LinearRegression

In [2]:
A=pd.DataFrame({'exp':[2.5,3.0,5.7,4.8,7.0,12,8],'g':[1,0,1,0,0,1,0],'sal':[6500,8000,4000,12000,10000,15000,6000]})
A

exp  g    sal
0   2.5  1   6500
1   3.0  0   8000
2   5.7  1   4000
3   4.8  0  12000
4   7.0  0  10000
5  12.0  1  15000
6   8.0  0   6000

In [3]:
x=A[['exp','g']]
y=A[['sal']]

In [4]:
m1=LinearRegression()
m1.fit(x,y)
y1_predict=m1.predict(x)
y1_predict

array([[ 5640.4109589 ],
       [ 7176.16761946],
       [ 7801.99007658],
       [ 8392.05587315],
       [ 9878.14151656],
       [12057.59896451],
       [10553.63499083]])

In [5]:
B=pd.DataFrame({'exp':[2.5,3.0,5.7,4.8,7.0,12,8],'g':[0,1,0,1,1,0,1],'sal':[6500,8000,4000,12000,10000,15000,6000]})
B

exp  g    sal
0   2.5  0   6500
1   3.0  1   8000
2   5.7  0   4000
3   4.8  1  12000
4   7.0  1  10000
5  12.0  0  15000
6   8.0  1   6000

In [6]:
x1=B[['exp','g']]
y1=B[['sal']]

In [7]:
m2=LinearRegression()
m2.fit(x1,y1)
y2_predict=m2.predict(x1)
y2_predict

array([[ 5640.4109589 ],
       [ 7176.16761946],
       [ 7801.99007658],
       [ 8392.05587315],
       [ 9878.14151656],
       [12057.59896451],
       [10553.63499083]])

In [9]:
new_col=A['exp']*A['g']
new_col
x=pd.concat([x,new_col],axis=1)

In [16]:
x.columns=['exp','g','exp:g']
m3=LinearRegression()
m3.fit(x,y)
y3_predict=m3.predict(x)
y3_predict

array([[ 4210.19403624],
       [10002.65251989],
       [ 7452.88200885],
       [ 9334.21750663],
       [ 8517.24137931],
       [13836.92395492],
       [ 8145.88859416]])

In [20]:
m3.intercept_

array([11116.71087533])

In [21]:
m3.coef_

array([[ -371.35278515, -9439.86681769,  1384.69277659]])

In [17]:
new_col2=B['exp']*B['g']
x1=pd.concat([x1,new_col2],axis=1)

In [19]:
x1.columns=['exp','g','exp:g']
m4=LinearRegression()
m4.fit(x1,y)
y4_predict=m4.predict(x1)
y4_predict

array([[ 4210.19403624],
       [10002.65251989],
       [ 7452.88200885],
       [ 9334.21750663],
       [ 8517.24137931],
       [13836.92395492],
       [ 8145.88859416]])

In [22]:
m4.intercept_

array([1676.84405764])

In [23]:
m4.coef_

array([[ 1013.33999144,  9439.86681769, -1384.69277659]])